version: '3.8'

services:
  mysql_master:
    image: mysql:8.3.0
    container_name: sharing_lab_01_mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: master_password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./data/master:/var/lib/mysql
      - ./config/master:/etc/mysql/conf.d
      - ./init/master:/docker-entrypoint-initdb.d
    networks:
      - sharing_lab_01

  mysql_slave:
    image: mysql:8.3.0
    container_name: sharing_lab_01_mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: slave_password
      MYSQL_DATABASE: mydatabase
    depends_on:
      - mysql_master
    ports:
      - "3307:3306"
    volumes:
      - ./data/slave:/var/lib/mysql
      - ./config/slave:/etc/mysql/conf.d
    networks:
      - sharing_lab_01

networks:
  sharing_lab_01:
