services:
  mysql_master:
    image: mysql:8.3.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - ./data/master:/var/lib/mysql
      - ./config/master:/etc/mysql/conf.d
      - ./init/master:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

  mysql_slave1:
    image: mysql:8.3.0
    container_name: mysql_slave1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    depends_on:
      - mysql_master
    ports:
      - "3307:3306"
    volumes:
      - ./data/slave1:/var/lib/mysql
      - ./config/slave1:/etc/mysql/conf.d
    networks:
      - mysql_network

networks:
  mysql_network:
